<a href="https://colab.research.google.com/github/GunduSriBhanu/data690_fall2022/blob/main/assignment_05/assignment_05_04_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# NumPy


In [1]:
# Import the numpy package under the name np
import sys
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.21.6



# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

## Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])



## Array Types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [17]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [18]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
c.dtype

dtype('<U1')

In [21]:
d = np.array([{'a': 1}, sys])

In [22]:
d.dtype

dtype('O')



## Dimensions and shapes

In [23]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [24]:
A.shape

(2, 3)

In [25]:
A.ndim

2

In [26]:
A.size

6

In [27]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [28]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [29]:
B.shape

(2, 2, 3)

In [30]:
B.ndim

3

In [31]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [32]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [33]:
C.dtype

dtype('O')

In [34]:
C.shape

(2,)

In [35]:
C.size

2

In [36]:
type(C[0])

list


## Indexing and Slicing of Matrices

In [37]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [38]:
A[1]

array([4, 5, 6])

In [39]:
A[1][0]

4

In [40]:
# A[d1, d2, d3, d4]

In [41]:
A[1, 0]

4

In [42]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [44]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [45]:
A[:2, 2:]

array([[3],
       [6]])

In [46]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
A[1] = np.array([10, 10, 10])

In [48]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [49]:
A[2] = 99

In [50]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])


## Summary statistics

In [51]:
a = np.array([1, 2, 3, 4])

In [52]:
a.sum()

10

In [53]:
a.mean()

2.5

In [54]:
a.std()

1.118033988749895

In [55]:
a.var()

1.25

In [56]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [57]:
A.sum()

45

In [58]:
A.mean()

5.0

In [59]:
A.std()

2.581988897471611

In [60]:
A.sum(axis=0)

array([12, 15, 18])

In [61]:
A.sum(axis=1)

array([ 6, 15, 24])

In [62]:
A.mean(axis=0)

array([4., 5., 6.])

In [63]:
A.mean(axis=1)

array([2., 5., 8.])

In [64]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [65]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...


## Broadcasting and Vectorized operations

In [66]:
a = np.arange(4)

In [67]:
a

array([0, 1, 2, 3])

In [68]:
a + 10

array([10, 11, 12, 13])

In [69]:
a * 10

array([ 0, 10, 20, 30])

In [70]:
a

array([0, 1, 2, 3])

In [71]:
a += 100

In [72]:
a

array([100, 101, 102, 103])

In [73]:
l = [0, 1, 2, 3]

In [74]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [75]:
a = np.arange(4)

In [76]:
a

array([0, 1, 2, 3])

In [77]:
b = np.array([10, 10, 10, 10])

In [78]:
b

array([10, 10, 10, 10])

In [79]:
a + b

array([10, 11, 12, 13])

In [80]:
a * b

array([ 0, 10, 20, 30])



## Boolean arrays
_(Also called masks)_

In [81]:
a = np.arange(4)

In [82]:
a

array([0, 1, 2, 3])

In [83]:
a[0], a[-1]

(0, 3)

In [84]:
a[[0, -1]]

array([0, 3])

In [85]:
a[[True, False, False, True]]

array([0, 3])

In [86]:
a

array([0, 1, 2, 3])

In [87]:
a >= 2

array([False, False,  True,  True])

In [88]:
a[a >= 2]

array([2, 3])

In [89]:
a.mean()

1.5

In [90]:
a[a > a.mean()]

array([2, 3])

In [91]:
a[~(a > a.mean())]

array([0, 1])

In [92]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [93]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [94]:
A = np.random.randint(100, size=(3, 3))

In [95]:
A

array([[98, 58, 29],
       [69, 15, 39],
       [67, 80, 26]])

In [96]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([98, 29, 15, 67, 26])

In [97]:
A > 30

array([[ True,  True, False],
       [ True, False,  True],
       [ True,  True, False]])

In [98]:
A[A > 30]

array([98, 58, 69, 39, 67, 80])



## Linear Algebra

In [99]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [100]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [101]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [102]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [103]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [104]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])


## Size of objects in Memory

### Int, floats

In [106]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [107]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [108]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [109]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [110]:
np.dtype(float).itemsize

8

### Lists are even larger

In [111]:
# A one-element list
sys.getsizeof([1])

80

In [112]:
# An array of one element in numpy
np.array([1]).nbytes

8

### And performance is also important

In [113]:
l = list(range(100000))

In [114]:
a = np.arange(100000)

In [115]:
%time np.sum(a ** 2)

CPU times: user 4.47 ms, sys: 0 ns, total: 4.47 ms
Wall time: 14.3 ms


333328333350000

In [116]:
%time sum([x ** 2 for x in l])

CPU times: user 93.6 ms, sys: 7.62 ms, total: 101 ms
Wall time: 205 ms


333328333350000



## Useful Numpy functions

### `random` 

In [117]:
np.random.random(size=2)

array([0.072871  , 0.50308474])

In [118]:
np.random.normal(size=2)

array([0.31169011, 0.48475649])

In [119]:
np.random.rand(2, 4)

array([[0.38352529, 0.66041517, 0.15011598, 0.74909898],
       [0.09295644, 0.94997896, 0.53981061, 0.07244564]])

---
### `arange`

In [120]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [122]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [123]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [124]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [125]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [126]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [127]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [128]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [129]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [130]:
np.zeros((3, 3), dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [131]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [132]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [133]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [134]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [135]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [136]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [137]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [138]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [139]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [140]:
"Hello World"[6]

'W'


## Array creation

### Create a numpy array of size 10, filled with zeros.

In [141]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


### Create a numpy array with values ranging from 10 to 49

In [142]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])



### Create a numpy matrix of 2*2 integers, filled with ones.

In [143]:
np.ones([2,2], dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[1, 1],
       [1, 1]])


### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [144]:
np.ones([3,2], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[1., 1.],
       [1., 1.],
       [1., 1.]])


### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [145]:
X = np.arange(4, dtype=np.int)

np.ones_like(X)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1, 1, 1, 1])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [146]:
# your code goes here


In [147]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(X)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0]])


### Create a numpy matrix of 4*4 integers, filled with fives.

In [148]:
# your code goes here


In [149]:
np.ones([4,4], dtype=np.int) * 5

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [150]:
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[7, 7],
       [7, 7]])


### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [151]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [152]:
np.random.randint(10, size=3)

array([5, 7, 4])



### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [153]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[-2.02062929, -0.91148275,  0.5222099 ],
        [-2.77181421, -0.58065248,  1.47547753],
        [ 0.8780484 ,  2.18244309,  1.36822808]],

       [[-0.77094831, -0.02036522, -2.31977947],
        [ 0.50413706,  0.45410718, -0.30119249],
        [-0.85908336, -0.12429302, -0.7501685 ]],

       [[ 1.15294801,  0.2358844 ,  0.2438943 ],
        [ 0.04935608,  0.10866901,  2.21457545],
        [ 2.74424784,  0.59128879, -0.87522657]]])



### Given the X python list convert it to an Y numpy array

In [154]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>




### Given the X numpy array, make a copy and store it on Y.

In [155]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 139910935799824
[5 2 3] 139910935800976


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.




### Create a numpy array with numbers from 1 to 10

In [156]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



### Create a numpy array with the odd numbers between 1 to 10

In [157]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])



### Create a numpy array with numbers from 1 to 10, in descending order.

In [158]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])



### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [159]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


### Show the memory size of the given Z numpy matrix

In [160]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes




## Array indexation


### Given the X numpy array, show it's first element

In [161]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'



### Given the X numpy array, show it's last element

In [162]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

'E'



### Given the X numpy array, show it's first three elements

In [163]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')



### Given the X numpy array, show all middle elements

In [164]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')


### Given the X numpy array, show the elements in reverse position

In [165]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')


### Given the X numpy array, show the elements in an odd position

In [166]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')


### Given the X numpy matrix, show the first row elements

In [167]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])


### Given the X numpy matrix, show the last row elements

In [168]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])



### Given the X numpy matrix, show the first element on first row

In [169]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1



### Given the X numpy matrix, show the last element on last row

In [170]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16



### Given the X numpy matrix, show the middle row elements

In [171]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])



### Given the X numpy matrix, show the first two elements on the first two rows

In [172]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])



### Given the X numpy matrix, show the last two elements on the last two rows

In [173]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])


## Array manipulation


### Convert the given integer numpy array to float

In [174]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


array([-5., -3.,  0., 10., 40.])


### Reverse the given numpy array (first element becomes last)

In [175]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]



### Order (sort) the given numpy array

In [176]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]



### Given the X numpy array, set the fifth element equal to 1

In [177]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])



### Given the X numpy array, change the 50 with a 40

In [178]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])



### Given the X numpy matrix, change the last row with all 1

In [179]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])



### Given the X numpy matrix, change the last item on the last row with a 0

In [180]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])



### Given the X numpy matrix, add 5 to every element

In [181]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])



## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [182]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])


### Given the X numpy array, get the negative elements

In [183]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])



### Given the X numpy array, get numbers higher than 5

In [184]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])



### Given the X numpy array, get numbers higher than the elements mean

In [185]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])


### Given the X numpy array, get numbers equal to 2 or 10

In [186]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])



## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [187]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False



### Given the X numpy array, return True if any of its elements is zero

In [188]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True



## Summary statistics

### Given the X numpy array, show the sum of its elements

In [189]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43


### Given the X numpy array, show the mean value of its elements

In [190]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7



### Given the X numpy matrix, show the sum of its columns

In [191]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])



### Given the X numpy matrix, show the mean value of its rows

In [192]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])


### Given the X numpy array, show the max value of its elements

In [193]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10